# Generated by Django 2.2.2 on 2019-06-24 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TB_EDU_UNIV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('loc', models.TextField()),
                ('uni_start', models.DateTimeField()),
                ('uni_end', models.DateTimeField()),
                ('day_yn', models.CharField(max_length=10)),
                ('category', models.TextField()),
                ('college', models.TextField()),
                ('transfer_yn', models.TextField()),
                ('major', models.TextField()),
                ('sub_major', models.TextField()),
                ('grade_cert', models.FileField(blank=True, upload_to='')),
                ('graduate_cert', models.FileField(blank=True, upload_to='')),
                ('attachments', models.FileField(blank=True, upload_to='')),
                ('total_score', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TB_USER_FILTER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_start', models.DateTimeField()),
                ('filter_end', models.DateTimeField()),
                ('sort', models.TextField()),
                ('category', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TB_REWARD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('organization', models.TextField()),
                ('reward_start', models.DateTimeField()),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TB_PROJECT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('project_start', models.DateTimeField()),
                ('project_end', models.DateTimeField()),
                ('order', models.TextField()),
                ('role', models.TextField()),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TB_GRADE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateTimeField()),
                ('semester', models.CharField(max_length=10)),
                ('major_yn', models.CharField(max_length=10)),
                ('credit', models.TextField()),
                ('name', models.TextField()),
                ('grade', models.CharField(max_length=5)),
                ('edu_univ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareers.TB_EDU_UNIV')),
            ],
        ),
        migrations.CreateModel(
            name='TB_ETC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('category', models.TextField()),
                ('content', models.TextField()),
                ('attachments', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TB_EDUCATION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('organization', models.TextField()),
                ('edu_start', models.DateTimeField()),
                ('edu_end', models.DateTimeField()),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TB_EDU_HIGH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('loc', models.TextField()),
                ('category', models.TextField()),
                ('high_start', models.DateTimeField()),
                ('high_end', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TB_CERT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField()),
                ('name', models.TextField()),
                ('organization', models.TextField()),
                ('cert_start', models.DateTimeField()),
                ('cert_end', models.DateTimeField()),
                ('score', models.TextField()),
                ('grade', models.TextField()),
                ('cert_num', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TB_CAREER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('dept', models.TextField()),
                ('loc', models.TextField()),
                ('careeer_start', models.DateTimeField()),
                ('careeer_end', models.DateTimeField()),
                ('position', models.TextField()),
                ('job', models.TextField()),
                ('salary', models.TextField()),
                ('tel', models.TextField()),
                ('email', models.TextField()),
                ('resign', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TB_BASIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('en_f_nm', models.TextField()),
                ('en_l_nm', models.TextField()),
                ('ch_nm', models.TextField()),
                ('birth', models.DateTimeField()),
                ('addr', models.TextField()),
                ('detail_addr', models.TextField()),
                ('zip_code', models.TextField()),
                ('phone1', models.TextField()),
                ('phone2', models.TextField()),
                ('sex', models.CharField(max_length=2)),
                ('email', models.TextField()),
                ('hobby', models.TextField()),
                ('speciality', models.TextField()),
                ('army_div', models.TextField()),
                ('army_group', models.TextField()),
                ('army_rank', models.TextField()),
                ('army_reason', models.TextField()),
                ('army_start', models.DateTimeField()),
                ('army_end', models.DateTimeField()),
                ('army_end_yn', models.TextField()),
                ('army_id', models.TextField()),
                ('army_etc', models.TextField()),
                ('martial_status', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
