# Generated by Django 2.2.2 on 2019-06-25 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycareers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_basic',
            name='army_end_yn',
        ),
    ]
