# Generated by Django 2.2.2 on 2019-06-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareers', '0002_remove_tb_basic_army_end_yn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_basic',
            name='addr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_basic',
            name='army_div',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_basic',
            name='army_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_basic',
            name='army_etc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_basic',
            name='army_group',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_basic',
            name='army_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_basic',
            name='army_rank',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_basic',
            name='army_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_basic',
            name='army_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_basic',
            name='birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_basic',
            name='ch_nm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_basic',
            name='detail_addr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_basic',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_basic',
            name='en_f_nm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_basic',
            name='en_l_nm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_basic',
            name='hobby',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_basic',
            name='martial_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_basic',
            name='phone1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_basic',
            name='phone2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_basic',
            name='sex',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tb_basic',
            name='speciality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_basic',
            name='user_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_basic',
            name='zip_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
