# Generated by Django 2.2.2 on 2019-06-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareers', '0003_auto_20190625_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_career',
            old_name='careeer_end',
            new_name='career_end',
        ),
        migrations.RenameField(
            model_name='tb_career',
            old_name='careeer_start',
            new_name='career_start',
        ),
        migrations.AddField(
            model_name='tb_edu_high',
            name='end_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tb_edu_high',
            name='start_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_career',
            name='dept',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_career',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_career',
            name='job',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_career',
            name='loc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_career',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_career',
            name='position',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_career',
            name='resign',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_career',
            name='salary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_career',
            name='tel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_cert',
            name='cert_num',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_cert',
            name='grade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_cert',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_cert',
            name='organization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_cert',
            name='score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_edu_high',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_edu_high',
            name='high_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_edu_high',
            name='high_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_edu_high',
            name='loc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_edu_high',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_edu_univ',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_edu_univ',
            name='college',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_edu_univ',
            name='loc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_edu_univ',
            name='major',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_edu_univ',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_edu_univ',
            name='sub_major',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_edu_univ',
            name='total_score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_edu_univ',
            name='transfer_yn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_edu_univ',
            name='uni_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_edu_univ',
            name='uni_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_education',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_education',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_education',
            name='organization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_grade',
            name='credit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_grade',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_project',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_project',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_project',
            name='order',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_project',
            name='role',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_project',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_reward',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_reward',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_reward',
            name='organization',
            field=models.TextField(blank=True, null=True),
        ),
    ]
