# Generated by Django 2.2.2 on 2019-06-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareers', '0006_auto_20190625_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_edu_univ',
            name='end_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_edu_univ',
            name='start_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
