# Generated by Django 2.2.2 on 2019-06-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareers', '0007_auto_20190625_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_grade',
            name='re_join',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_grade',
            name='grade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_grade',
            name='major_yn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_grade',
            name='semester',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_grade',
            name='year',
            field=models.TextField(blank=True, null=True),
        ),
    ]
