# Generated by Django 2.2.2 on 2019-06-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareers', '0009_auto_20190626_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_cert',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
