# Generated by Django 2.2.2 on 2019-06-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareers', '0010_auto_20190626_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_education',
            name='edu_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_education',
            name='edu_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_project',
            name='project_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_project',
            name='project_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_reward',
            name='reward_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
