# Generated by Django 2.2.2 on 2019-06-26 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycareers', '0013_auto_20190626_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_project',
            old_name='project_start',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='tb_reward',
            old_name='reward_start',
            new_name='start',
        ),
    ]
