# Generated by Django 2.2.2 on 2019-06-27 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycareers', '0015_auto_20190626_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_edu_univ',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='tb_edu_univ',
            name='grade_cert',
        ),
        migrations.RemoveField(
            model_name='tb_edu_univ',
            name='graduate_cert',
        ),
    ]
